[IMP] claim CLM8676
avanzosc/education pull request #165
Opened 2020-09-30 13:14 UTC by adrianrevilla009

Reclamación CLM8676. Añadir campos email y teléfonos a la vista education.res_partner_education_minimal_photo_view_form

2020-09-30 14:15 UTC, oihane requested changes

2020-09-30 14:15 UTC, oihane commented on education/views/res_partner_view.xml
> +                    <field name="email"/>
Tienes que meterlo dentro de un group, si no, no mostrará la etiqueta en la vista

2020-10-01 05:31 UTC, adrianrevilla009 commented on education/views/res_partner_view.xml
> +                    <field name="email"/>
Modificado @oihane

2020-10-01 07:53 UTC, anajuaristi approved these changes

2020-10-01 08:43 UTC, oihane approved these changes

2020-10-01 08:44 UTC, merged