[ADD] New module account_invoice_validate_vendor_lines
avanzosc/education pull request #166
Opened 2020-09-30 16:55 UTC by leiremartinezdesantos

2020-10-01 08:35 UTC, oihane requested changes
Revisa el modulo, puede que haya comentarios repetidos o también cosas no comentadas porque se repiten. Además necesitas revisar dependencias, como estas trabajando sobre la base de datos del cliente no te da error pero si intentas instalar este modulo en una base de datos NUEVA, te daría error por la falta de center_id en el producto (modulo "sale_school")

@anajuaristi, este modulo deberá depender de _sale_school_ aún siendo para facturas de compra.

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/models/account_invoice.py
> +        self.validate_OK = all(self.invoice_line_ids.mapped("validate_OK"))
* Los campos calculados se hacen multi.
* La función se suele llamar _compute_nombrecampo
* los campos se usan en minuscula

```python
    @api.multi
    @api.depends("invoice_line_ids", "invoice_line_ids.validate_OK")
    def _compute_validate_ok(self):
        for record in self:
            record.validate_ok = all(record.mapped("invoice_line_ids.validate_ok"))
```

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/__init__.py
> +# -*- coding: utf-8 -*-
No es necesario

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/__init__.py
> +from . import models
Te falta un salto de linea (conviene que después de hacer una subida lo primero que hagas es un auto review)

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/__manifest__.py
> +# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
Has copiado y aquí has añadido mi licencia

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/models/account_invoice.py
> +# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html
Pero en este otro el de Adrian

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/models/account_invoice.py
> +from odoo import fields, models, api
Acostúmbrate a poner en orden alfabético (OCA empezó a pedirlo)

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/models/account_invoice_line.py
> +    center_id = fields.Many2one(comodel_name="product.product", related='product_id.company_id')
Este enlace es incorrecto

1. centro es res.partner / has puesto el comodel como "product.product"
2. compañia del producto es res.company / lo mismo, impactaría con el comodel seleccionado
3. en realidad tienes que poner:
   center_id = fields.Many2one(comodel_name="res.partner", related="product_id.center_id", store=True)

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/models/account_invoice_line.py
> +
Llámalo **toggle_validate_ok** 

te sobran lineas en blanco

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_filter.xml
> +        <field name="name">account.invoice.validate.filter</field>
No es necesario el name, eliminalo

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_filter.xml
> +</odoo>
Salto de línea

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_filter.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
El nombre del fichero debería de ser **account_invoice_view.xml**

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_line_view.xml
> +    </record>
La vista es de account.invoice, por lo que deberias de añadir al fichero account_invoice_view.xml

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_line_view.xml
> +        <field name="name">account.invoice.line.validate.form</field>
eliminar nombre

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_view.xml
> +        <field name="name">account.invoice.validate.tree</field>
eliminar nombre

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_view.xml
> +        <field name="name">account.invoice.validate.form</field>
eliminar nombre

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_view.xml
> +                <field name="validate_OK" string="Validated OK"/>
El _string_ se pone cuando el nombre del campo no es igual a lo que quieres poner en la vista

2020-10-01 08:35 UTC, oihane commented on account_invoice_validate_vendor_lines/views/account_invoice_view.xml
> +</odoo>
Salto de línea

2020-10-01 08:41 UTC, oihane commented
Te está fallando travis:
PEP8 - FLAKE8
```
account_invoice_validate_vendor_lines/models/account_invoice.py:16:1: W391 blank line at end of file
account_invoice_validate_vendor_lines/models/account_invoice_line.py:10:32: E128 continuation line under-indented for visual indent
account_invoice_validate_vendor_lines/models/account_invoice_line.py:12:80: E501 line too long (96 > 79 characters)
account_invoice_validate_vendor_lines/models/account_invoice_line.py:20:1: W391 blank line at end of file
```

PYLINT (son avisos)
```
************* Module account_invoice_validate_vendor_lines
account_invoice_validate_vendor_lines/__init__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
account_invoice_validate_vendor_lines/views/account_invoice_view.xml:1: [W7908(missing-newline-extrafiles), ]  Missing newline
account_invoice_validate_vendor_lines/views/account_invoice_filter.xml:1: [W7908(missing-newline-extrafiles), ]  Missing newline
************* Module account_invoice_validate_vendor_lines.models.account_invoice
account_invoice_validate_vendor_lines/models/account_invoice.py:9: [C8108(method-compute), AccountInvoice] Name of compute method should start with "_compute_"
account_invoice_validate_vendor_lines/models/account_invoice.py:14: [W8104(api-one-deprecated), AccountInvoice.check_value] api.one deprecated
```

Y al hacer los test porque el comodel no coincide también falla
```
` ValueError: Wrong value for account.invoice.line.center_id: res.company(1,)
```

2020-10-01 08:41 UTC, oihane commented
El modulo debería de ir a la rama odoo-addons, y con nombre singular, falta también las traducciones

2020-10-07 09:53 UTC, oihane commented on account_invoice_validate_vendor_line/models/account_invoice_line.py
> +                                 default=False, required=True)
Los campos booleanos con required, no traen más que problemas :wink:

2020-10-07 09:53 UTC, oihane commented on account_invoice_validate_vendor_line/models/account_invoice_line.py
> +        self.validate_ok = not self.validate_ok
Hay que poner un for

```python
for record in self:
    record.validate_ok = not record.validate_ok
```

2020-10-07 09:56 UTC, oihane commented on account_invoice_validate_vendor_line/views/account_invoice_view.xml
> +                <filter string="Validated NOK" name="_compute_validate_ok" domain="[('validate_ok','=', False)]" />
Primero:
No pueden tener el mismo nombre, esto se usa para marcar uno por defecto por ejemplo

Segundo:
puedes poner validate y no_validate, y basandote en eso el string (Validated NOK no tiene mucho sentido)

2020-10-07 13:15 UTC, oihane commented
account_invoice_validate_vendor_line/models/account_invoice.py:27:80: E501 line too long (80 > 79 characters)

2020-10-07 15:08 UTC, oihane commented on account_invoice_validate_vendor_line/models/account_invoice.py
> +                                    "=", False))
Duplicado

2020-10-07 15:32 UTC, oihane approved these changes
LGTM

2020-10-08 05:17 UTC, alfredoavanzosc approved these changes
:+1:

2020-10-15 14:09 UTC, oihane commented on account_invoice_validate_vendor_line/__manifest__.py
> +        "education",
estas dependencias fuera

2020-10-15 14:09 UTC, oihane commented on account_invoice_validate_vendor_line/models/account_invoice.py
> +        compute='_compute_school_ids', store=True)
esto tambien fuera

2020-10-15 14:09 UTC, oihane commented on account_invoice_validate_vendor_line/models/account_invoice.py
> +                'invoice_line_ids.product_center_id')
quitar

2020-10-15 14:10 UTC, oihane commented on account_invoice_validate_vendor_line/models/account_invoice.py
> +                all(record.mapped("invoice_line_ids.validate_ok"))
Mejor poner 

```python
            record.validate_ok = all(
                record.mapped("invoice_line_ids.validate_ok"))
```

2020-10-15 14:10 UTC, oihane commented on account_invoice_validate_vendor_line/models/account_invoice_line.py
> +        related="product_id.center_id", store=True)
eliminar

2020-10-15 14:11 UTC, oihane commented on account_invoice_validate_vendor_line/views/account_invoice_line_view.xml
> +                <field name="product_center_id"  widget="res_partner_many2one" />
Eliminar

2020-10-15 14:11 UTC, oihane commented on account_invoice_validate_vendor_line/views/account_invoice_view.xml
> +            </field>
eliminar

2020-10-15 14:11 UTC, oihane commented on account_invoice_validate_vendor_line/views/account_invoice_view.xml
> +            </field>
quitar

2020-10-15 14:11 UTC, oihane commented on account_invoice_validate_vendor_line/views/account_invoice_view.xml
> +                <field name="line_school_ids" widget="many2many_tags" />
fuera...

2020-10-15 14:11 UTC, oihane commented on account_invoice_validate_vendor_line/views/account_invoice_view.xml
> +            </xpath>
borrar

2020-11-11 10:38 UTC, closed without merging