[IMP] education_evaluation_notebook: added new relations
avanzosc/education pull request #187
Opened 2020-10-22 12:23 UTC by leiremartinezdesantos

Added relation to Global and Evaluation lines on Education Records.

2020-10-22 12:34 UTC, oihane requested changes

2020-10-22 12:34 UTC, oihane commented on education_evaluation_notebook/models/education_record.py
> +        string="Is Evaluation Competence", store=True)
Esto no lo cambies

2020-10-22 12:34 UTC, oihane commented on education_evaluation_notebook/models/education_record.py
> +        string="Is Global Competence", store=True)
Déjalo como estaba

2020-10-22 12:34 UTC, oihane commented on education_evaluation_notebook/models/education_record.py
> +        string="Global Notebook Line", store=True)
Pon delante de `line_`: `line_parent_id` y `line_parent_parent_id`

2020-10-23 09:09 UTC, oihane approved these changes

2020-10-23 09:10 UTC, Daniel-CA approved these changes

2020-10-23 09:23 UTC, merged