[FIX] education_evaluation_notebook
avanzosc/education pull request #41
Opened 2019-11-07 11:58 UTC by adrianrevilla009

2019-11-07 12:05 UTC, oihane commented on education_evaluation_notebook/__init__.py
> +from . import models
No se pone el copyright porque no tiene "código" y te falta un salto de línea al final

2019-11-07 12:06 UTC, oihane commented on education_evaluation_notebook/__manifest__.py
> +# Copyright (c) 2019 Adrian Revilla <adrianrevilla@avanzosc.es> - Avanzosc S.L.
Sobra el poner la `(c)` y el correo, ya que el correo se añade en el readme poniendote como contributor

2019-11-07 12:07 UTC, oihane commented on education_evaluation_notebook/__manifest__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
La dirección que se usa es `https://www.gnu.org/licenses/agpl.html`

2019-11-07 12:07 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_competence.py
> +from odoo import fields, models, api
Las importaciones en orden alfabético

2019-11-07 12:08 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_competence.py
> +class educationCompetence(models.Model):
El nombre de la clase se pone UpperCamelCase

2019-11-07 12:14 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_competence.py
> +        return result
Falta el salto de línea

2019-11-07 12:14 UTC, oihane commented on education_evaluation_notebook/views/education_notebook_competence_view.xml
> +<?xml version="1.0" encoding="utf-8"?>
En los XML usa tambien la tabulación por 4 espacios, como el los ficheros Python que luego al revisar cambios ocupa menos el diff

2019-11-07 12:14 UTC, oihane commented on education_evaluation_notebook/views/education_notebook_exam_view.xml
> +</odoo>
En los XML tambien hay que poner salto de línea, aunque esto no da error

2019-11-07 12:14 UTC, oihane commented on education_evaluation_notebook/README.rst
> +==================
Las líneas de `=` deben de ser TAN LARGAS como la frase que se quiere formatear.

2019-11-07 12:27 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +        for exam in self:
Creo que aquí te has colado
```python
    @api.multi
    def name_get(self):
        result = []
        for record in self:
            result.append((record.id, '[Exam] {}'.format(
                 record.exam_type.name)))
        return result
 ```

2019-11-07 12:53 UTC, adrianrevilla009 commented on education_evaluation_notebook/__manifest__.py
> +# Copyright (c) 2019 Adrian Revilla <adrianrevilla@avanzosc.es> - Avanzosc S.L.
Solo en el manifest? En todos los .py también?

2019-11-07 12:55 UTC, anajuaristi submitted a review, later dismissed

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +            exam_id = exam.env['education.exam'].search([('id', '=', exam.id)])
Al estar haciendo for exam in self, ya tienes el id de examen por lo que el search sobra.
y tampoco necesitarías la variable exam_id, simplemente donde la necesites usas exam.id y ya está

@oihane valida lo que digo si es así.

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +            if exam_id:
if exam --> No sería en principio necesario porque ya estás haciendo un for sobre el objeto, por tanto existe

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                    write_line = exam.env['education.expedient']
vería mejor expedient_line en el nombre

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                        'id':exam.id,
El ID de expediente lo vas a crear en el create de dicho objeto por lo que no le puedes asignar el id del examen, elimina la línea

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                        'exam_id': exam_id.n_line.id,
'exam_id' : exam.id

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                kid_ids = exam.n_line.planification_id.student_ids
en vez de kid_ids, sería kids, dado que estás cogiendo el browse record (registro completo) en vez de el id
Es decir... sería
```python
kid_ids = exam.n_line.planification_id.mapped('student_ids').ids  #--> con esto coges el listado de ids
kids = exam.n_line.planification_id.student_ids #--> con esto coges todos los datos de los registros de student_ids
```

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                    for record in kid_ids:
'```
for kid in kids
'```

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                        'date': exam_id.date,
En todos estos, al haber eliminado la variable exam_id de arriba, basta con que pongas exam.date, exam.

Pero aparte de esto, todos los datos que estás llevando al expediente son related al niño o al examen, por lo que no es necesario que los traigas al expediente como valor. Queda algo muy simple como 

```python
line_data = { #cambia el nombre a expedient_line_data
      'exam_id': exam.id,
      'kid_id': kid.id,
```

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                    if not exam.n_line:
Puesto que el profe no se trae, sino que se mostrará de forma related, no es necesario controlar el error.

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_line.py
> +    teacher = fields.Char(related='planification_id.teacher_id.name',
```python
 teacher_id = fields.Many2one(related='planification_id.teacher_id', comodel_name='hr.employee', string='Teacher', store=True)
```

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_line.py
> +    a_year = fields.Char(related='planification_id.academic_year_id.name',
lo mismo con todos los demás. En los campos related, se trae el objeto completo con el que estás relacionando. Un campo related normalmente no es un Char, la mayoría de las veces es un many2one. Si no lo es, se suele indicar en los requerimientos.

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_line.py
> +            if not record.exam_ids:
record.num_exams = len(record.exam_ids)
con poner únicamente esto, es suficiente. El if no hace falta. Si exam_ids está vacío, el len es cero

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_stuff.py
> +    def name_get(self):
No hace falta el name_get aquí. En los sitios donde mostremos la nota, los 4 campos serán related. Tienen que ir aparte.

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_stuff.py
> +    )
```
name= fields.Char()
code = fields.Selection(
    [('A', 'Very Good'),
     ('B', 'Good'),
     ('C', 'Normal'),
     ('D', 'Bad'),], string='Code', default='B', required=True)
```

2019-11-07 12:55 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_stuff.py
> +            result.append((record.id, '[Behaviour mark] {}'.format(
'[Behaviour mark] {} {}'

2019-11-07 13:01 UTC, oihane requested changes

2019-11-07 13:01 UTC, oihane commented on education_evaluation_notebook/models/education_schedule.py
> +    notebook_lines_count = fields.Integer(compute='_count_notebook_lines',
El travis te va a obligar a poner
`compute='_compute_notebook_lines_count'`

2019-11-07 13:01 UTC, oihane commented on education_evaluation_notebook/models/education_schedule.py
> +    def _count_notebook_lines(self):
Un compute debe de ser `@api.multi` al menos, porque lo normal es que si no es persistente (`store=False`) se muestre únicamente entrando en uno (vista form), pero puede ser mostrado en el tree, por lo que se calcula de manera multiple.

```python
    @api.multi
    def _compute_notebook_lines_count(self):
        notebook_line_obj = self.env['education.notebook.line']
        for schedule in self:
            schedule.notebook_lines_count = notebook_line_obj.search_count([
                ('planification_id', '=', schedule.id)])
```

2019-11-07 13:04 UTC, oihane commented on education_evaluation_notebook/__manifest__.py
> +# Copyright (c) 2019 Adrian Revilla <adrianrevilla@avanzosc.es> - Avanzosc S.L.
En todos los *.py

2019-11-07 13:15 UTC, oihane requested changes

2019-11-07 13:15 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +    _description = 'Educational exams'
```python
_description = 'Education Exam'
```

2019-11-07 13:15 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +    exam_type = fields.Many2one(comodel_name='education.exam.type',
Cuando se hace un **Many2one** el nombre del campo debe incluir `_id`
Cuando se hace un **Many2many** el nombre del campo debe incluir `_ids`

2019-11-07 13:15 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +            exam.clear_messages()
¿¿porque eliminas aquí tambien los mensajes??

2019-11-07 13:26 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_expedient.py
> +    _description = 'Educational expedient'
Dado que se trata de un expediente académico, yo usaría:

```python
_name = 'education.record'
_description = 'Academic Record'
```
El name, es el nombre técnico del objeto, como "cuelga" de education, puedes usarlo así, mientras que description se usa para nombrar al objeto y es para cuando andas en el sistema. El mejor ejemplo es [este](https://github.com/odoo/odoo/blob/a9c2f35c5dac5cf629e5219c604cfc39ca68de4a/odoo/addons/base/models/res_partner.py#L133)
```python
class Partner(models.Model):
    _description = 'Contact'
    _name = "res.partner"
```

EXPEDIENT no existe en ingles, en [Linguee](https://www.linguee.es) puedes mirar como se dice ["Expediente académico"](https://www.linguee.es/espanol-ingles/traduccion/expediente+acad%C3%A9mico.html)

2019-11-07 14:48 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_stuff.py
> +            result.append((record.id, '[Behaviour mark] {}'.format(
acabo de encontrarlo, como explicación
https://www.geeksforgeeks.org/python-format-function/

2019-11-08 07:18 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                        'exam_id': exam_id.n_line.id,
Todo corregido menos esto. 
Un education.record define el exam_id como si fuera una linea de cuaderno del profesor (ya que así se dijo (si hay que modificarlo comentame)).
Por tanto debe ser exam.n_line.id. Lo que voy a hacer es cambiarle el nombre al string con el que se identifica por algo más descriptivo para evitar confusiones.

2019-11-08 08:53 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                        'exam_id': exam_id.n_line.id,
Como ya te ha comentado Ana en algún otro sitio, si el campos se llama **exam_id** la relación debería de ser con **exam**, y es eso lo que lleva a error. Veo que has realizado el cambio de nombre de variable, por lo que @anajuaristi esto solucionado.

### Por favor, no hagas la subida con amend y un forzado, porque se pierden donde estaban colocados estos comentarios. Cuando se vaya a mergear se puede fusionar los commits en uno solo.

2019-11-08 09:10 UTC, oihane requested changes
Otro poco más

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/__init__.py
> +
elimina estas líneas en blanco no sirven para nada

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/__init__.py
> +# Copyright (c) 2019 Adrian Revilla <adrianrevilla@avanzosc.es> - Avanzosc S.L.
Sobra, solo importaciones no necesita que haya ni licencia ni atribuciones

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_competence.py
> +# Copyright (c) 2019 Adrian Revilla <adrianrevilla@avanzosc.es> - Avanzosc S.L.
Sobra la (c) y el correo

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_competence.py
> +    )
Para que vayas acostumbrandote, en OCA lo piden debes de nombrar cada uno de los atributos, en este caso poner el `selection=`
```python
eval_mode = fields.Selection(selection=[
        ('numeric', 'Numeric'),
        ('behaviour', 'Behaviour'),
        ('both', 'Both')],
        string='Evaluation mode', default='numeric', required=True)
```

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_competence.py
> +        return result
Para mí esto no es necesario, ya que donde vayas a usarlo ya pondrá que es una competencia y no otra cosa.

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +    eval_percent = fields.Integer(string='Percent (%)',required=True)
Varias cosas, ten en cuenta las indentaciones, que entre atributos la coma debe ir con un espacio, y que en ingles se pone **associated**, pero no estoy segura de que ese nombre tenga sentido si lo que enlazas es una línea del cuaderno
```python
    exam_type_id = fields.Many2one(comodel_name='education.exam.type',
                                   string='Exam type', required=True)
    n_line_id = fields.Many2one(comodel_name='education.notebook.line', 
                                string='Exam asociated competence',
                                ondelete='cascade')
    eval_type = fields.Selection(related='n_line_id.eval_type',
                                 string='Evaluation season')
    date = fields.Date(string='Exam date', required=True)
    eval_percent = fields.Integer(string='Percent (%)', required=True)
```

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +            ],default='notgenerated')
Lo mismo que antes de falta el `selection=` y un espacio por delante del  `default=`

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +        return result
Lo mismo, creo que sobra ponerle `[Exam]`

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                    'teacher_id': exam.n_line_id.planification_id.teacher_id.id,
Son campos `related` no tienes porque 'informarlos' se rellenarán aútomaticamente.

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                        exam.write({'state': 'notgenerated',})
```python
exam.write({
    'message_error': _('Error generating academic record lines!'),
    'state': 'notgenerated',
})
```

* además deberas importar en la cabecera `_` que sirve para realizar traducciones
```python
from odoo import _
```

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                exam.write({'state': 'generated',})
```python
exam.write({
    'message_error': _('Academic record lines generated successfully!'),
    'state': 'generated',
})
```

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                exam.write({'state': 'notgenerated',})
```python
exam.write({
    'message_error': _(''Not kids for this exam to generate academic record!''),
    'state': 'notgenerated',
})
```

2019-11-08 09:10 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_stuff.py
> +
Falta un salto de línea

2019-11-08 11:23 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_stuff.py
> +
entendidos últimos cambios, gracias

2019-11-25 09:50 UTC, Daniel-CA commented on education_evaluation_notebook/models/education_notebook_record.py
> +            if record.numeric_mark >= 0.0 and record.numeric_mark < 2.5:
Estas "numeric_mark" no deberían ser "configurables". Por si en el futuro cambian la numeración o quiere utilizar otro tipo de "mark_code", sin que haya que tocar el código.

2019-11-27 09:13 UTC, oihane requested changes
Unas cosillas por ahora

2019-11-27 09:13 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_competence.py
> +    def name_get(self):
Elimina el name_get, no es necesario

2019-11-27 09:13 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +    @api.depends('competence_id','father_competence_id')
El `@api.depends` es para los campos compute, si es un constraint no hay que ponerlo

2019-11-27 09:13 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +    @api.one
Has puesto `@api.one` y luego has añadido un for, eso no es correcto, aparte de que no se pone `@api.one`

2019-11-29 08:45 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +    a_year = fields.Char(related='planification_id.academic_year_id.name',
@anajuaristi un campo related es del mismo tipo que aquello relacionado. Por ejemplo, puedes hacer un campo partner_name en el usuario, haciendo el related a traves del many2one del partner_id y trayendo el name que es un char

2019-11-29 10:02 UTC, oihane requested changes

2019-11-29 10:02 UTC, oihane commented on education_evaluation_notebook/models/education_academic_year.py
> +                                     inverse_name='a_year', required=True)
He integrado las evaluaciones en el código del módulo 'education' por lo que puedes eliminar este fichero

2019-11-29 10:02 UTC, oihane commented on education_evaluation_notebook/models/education_academic_year_evaluation.py
> +
Ahora el módulo 'education' lo crea, por lo que lo puedes eliminar.

2019-11-29 10:02 UTC, oihane commented on education_evaluation_notebook/views/education_notebook_menu_view.xml
> +                  />
Integrado en el modulo 'education'

2019-11-29 10:02 UTC, oihane commented on education_evaluation_notebook/views/education_notebook_menu_view.xml
> +        </record>
Eliminar

2019-11-29 10:02 UTC, oihane commented on education_evaluation_notebook/views/education_academic_year_evaluation.xml
> +</odoo>
Eliminar el fichero completo

2019-11-29 10:02 UTC, oihane commented on education_evaluation_notebook/views/education_academic_year.xml
> +</odoo>
Eliminar fichero

2019-11-29 10:02 UTC, oihane commented on education_evaluation_notebook/security/ir.model.access.csv
> +education_academic_year_evaluation_user,education_academic_year_evaluation user,model_education_academic_year_evaluation,base.group_user,1,1,1,1
Eliminar líneas integradas en el módulo 'education'

2019-12-02 08:04 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_academic_year.py
> +                                     inverse_name='a_year', required=True)
de acuerdo.

2019-12-02 09:51 UTC, oihane requested changes

2019-12-02 09:51 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +    @api.onchange('competence_id')
En los computed no se pone onchange, se pone depends, y funciona igual que el onchange.

2019-12-02 09:51 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +        self.exams_academic_records_count = count
```python
    @api.multi
    @api.depends('exam_ids')
    def _compute_exams_academic_records_count(self):
        record_obj = self.env['education.record']
        for line in self:
            line.exam_academic_records_count = record_obj.search_count([
                ('exam_id', 'in', line.exam_ids.ids)])
```

2019-12-02 09:51 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +            record.num_exams = len(record.exam_ids)
Los campos computed SIEMPRE como `@api.multi`

2019-12-02 11:10 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_line.py
> +    @api.onchange('competence_id')
todos cambios aplicados menos este.
No me funciona con depends, en cambio con onchange si que lo hace.

2019-12-02 11:52 UTC, oihane commented on education_evaluation_notebook/models/education_academic_year.py
> +                                string='Course', required=True)
No puedes ponerlos requeridos en el python, a no ser que pongas un default, ya que el objeto se crea en otro modulo y puede que no tenga valor cuando se instale este modulo, y por lo tanto no podrá aplicar el requerido.

2019-12-02 11:52 UTC, oihane commented on education_evaluation_notebook/models/education_academic_year.py
> +    school = fields.Many2one(comodel_name='res.partner',
Si es un many2one se pone school_id

2019-12-02 11:53 UTC, oihane commented on education_evaluation_notebook/models/education_academic_year.py
> +    course = fields.Many2one(comodel_name='education.course',
Si es un many2one se pone course_id

2019-12-02 11:53 UTC, oihane commented on education_evaluation_notebook/models/education_academic_year.py
> +
Te falta un salto de línea

2019-12-02 11:53 UTC, oihane commented on education_evaluation_notebook/models/education_academic_year.py
> +from odoo import api, exceptions, fields, models, _
No tienes que importarlo todo solo models y fields

2019-12-02 13:11 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +    @api.depends('competence_id')
```python
@api.depends('competence_id', 'competence_id.evaluation_check', 'competence_id.global_check')
```

2019-12-02 13:12 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_record.py
> +    @api.onchange('numeric_mark')
Debes de añadir el compute al campo, si no, se trata de un onchange no de un campo compute

2019-12-02 13:14 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_record.py
> +    @api.depends('exam_id')
```python
@api.depends('exam_id', 'exam_id.eval_percent', 'n_line_id', 'n_line_id.eval_percent')
```

2019-12-02 13:15 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_record.py
> +                record.exam_eval_percent = record.n_line_id.eval_percent
```python
record.exam_eval_percent = record.exam_id.eval_percent if record.exam_id else record.n_line_id.eval_percent
```

2019-12-05 12:02 UTC, oihane commented on education_evaluation_notebook/views/education_notebook_homework_view.xml
> +			</header>
El header debe de ir dentro del form

```
odoo.tools.convert.ParseError: "Wrong value for ir.ui.view.type: 'data'" while parsing /home/travis/build/avanzosc/education/education_evaluation_notebook/views/education_notebook_homework_view.xml:5, near
<record id="education_notebook_homework_view_form" model="ir.ui.view">
		<field name="model">education.homework</field>
		<field name="arch" type="xml">
			<data><header>
				<button name="action_generate_homework_competence" string="Generate homework competence" type="object" class="btn btn-success"/>
			</header>
			<form string="Homework">
				<sheet>
					<group string="Homework fields">
						<field name="description"/>
						<field name="date"/>
						<field name="planification_id"/>
					</group>
					<group>
					</group>
				</sheet>
			</form>
		</data></field>
	</record>
```

2019-12-05 12:24 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_record.py
> +                    recuperation_exam_record.calculated_numeric_mark = recuperation_exam_record.numeric_mark * (recuperation_exam_record.exam_eval_percent/100)
```python
for record in self:
    record.calculated_numeric_mark = sum([
        r.numeric_mark * r.exam_eval_percent / 100 for r in record.child_record_ids])
```

2019-12-05 12:25 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_record.py
> +                 'numeric_mark', 'exam_eval_percent', 'child_record_ids')
```python
@api.depends('child_record_ids', 'child_record_ids.numeric_mark', 'child_record_ids.exam_eval_percent')
```

2019-12-05 12:50 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_record.py
> +                 'numeric_mark', 'exam_eval_percent', 'child_record_ids')
recibido, tengo que echar un vistazo a todos los depends para ver si estan correctos.

2019-12-09 09:05 UTC, oihane commented on education_evaluation_notebook/views/education_notebook_competence_view.xml
> +		<sheet>
`<sheet>` va dentro de `<form>`

2019-12-09 17:20 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_record.py
> +            if record.master_competence_global_check:
Todo esto no hace falta.
El compute, solo es la suma del %*nota manual de los hijos en cualquier caso. Siempre, sea la línea del tipo que sea.

2019-12-09 17:20 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_homework.py
> +    def action_generate_homework_competence(self):
Esto no hace falta. El profe, si lo necesita lo crea a mano

2019-12-09 17:20 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                parent_record = n_line.create_student_record(student)
Aquí haría el search según me dices. Yo cambiaría el nombre create_student_record por simplemente student_record

2019-12-09 17:20 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_homework.py
> +
Aquí faltaría simplemente un shortcut desde la planificación a los home work con vistas calendar y tree.
Al crear un homework, asignaría la planificación desde la que se ha accedido al objeto. Dicha planificación es no editable.
No se podrán crear homeworks desde ningún otro sitio que no sea desde la planificación.

2019-12-09 17:20 UTC, anajuaristi commented on education_evaluation_notebook/models/education_notebook_line.py
> +    # academic_record_ids = fields.One2many(comodel_name='education.record',
Este one2many SI haría falta.
Existen academic records que van directamente desde el notebook line, sin examen. Serían los de competencia, los evaluation y los global.

2019-12-09 17:20 UTC, anajuaristi commented on education_evaluation_notebook/models/education_schedule.py
> +    def update_son_competence_lines(self, notebook_line_global_comp, notebook_line_eval_first, notebook_line_eval_second, notebook_line_eval_third, notebook_line_son_first, notebook_line_son_second,
Hau zer da???
Egin beharko luke... evaluation lista hartu eta horren arabera sortu konpetentziak ez?
Hau hardcode dago.

2019-12-09 17:20 UTC, anajuaristi commented on education_evaluation_notebook/models/education_schedule.py
> +    def generate_global_academic_record(self, n_line_id):
Hau funtzio bakar batekin eta parametroak pasatuz egin daiteke. Uste det.
Hau da.. funtzio bakarra 
generate_academic_record --> sin más. 
Competentzi batetik badoa exam_id da null eta % hartu behar du conpetentzitik
Exam batetik badoa, exam_id izango da ezberdin null eta % hartu behar du azterketatik.
Baino bestela berdinak die kasu danetan.

2019-12-09 17:34 UTC, oihane commented on education_evaluation_notebook/models/education_notebook_line.py
> +    # academic_record_ids = fields.One2many(comodel_name='education.record',
Solo es necesario si lo vas a mostrar en la vista

2019-12-10 07:54 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_record.py
> +            if record.master_competence_global_check:
El "if" que me comentas es de la versión anterior a la que subí. Te refieres a que también debo quitar el bucle? Suponiendo que cuando cambias una nota se deben recalcular todas las demás, no sería necesario?

2019-12-10 07:58 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_homework.py
> +    def action_generate_homework_competence(self):
En el enunciado que me pasaste ponía lo siguiente "Si en algún caso la realización de deberes influye en la nota de la asignatura, el profe creará la correspondiente competencia, con un examen "ficticio" realización de deberes al que le pondrá nota" y lo interpreté con que tenía que meter un botón para generar.
Por tanto no es necesario, elimino esta funcionalidad?

2019-12-10 08:03 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_exam.py
> +                parent_record = n_line.create_student_record(student)
Este código no se encuentra en lo último que he subido.

2019-12-10 08:46 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_homework.py
> +
Listo

2019-12-10 08:47 UTC, adrianrevilla009 commented on education_evaluation_notebook/models/education_notebook_line.py
> +    # academic_record_ids = fields.One2many(comodel_name='education.record',
Ese field existe, solo que está comentado en una versión anterior a la última que he subido.

2020-01-21 14:57 UTC, Daniel-CA approved these changes

2020-01-21 15:00 UTC, oihane approved these changes

2020-01-21 15:01 UTC, merged